-- Create a table for public profiles linkable to auth.users
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  business_name text,
  business_type text,
  default_tone text,
  
  constraint username_length check (char_length(business_name) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table to track generations
create table generations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  review_content text,
  response_content text,
  tone_used text
);

alter table generations enable row level security;

create policy "Users can view their own generations." on generations
  for select using (auth.uid() = user_id);

create policy "Users can insert their own generations." on generations
  for insert with check (auth.uid() = user_id);
